### PR TITLE
Malformed attribute crash fix

### LINKED ISSUE #2: IOC crashes when passed malformed NDAttribute
When an NDAttribute has no data type specified and ADPluginKafka is enabled, the IOC will crash with an assertion.

## Steps to reproduce

1. Build an IOC with ADPluignKafka and any areaDetector modules
2. Create an `attributes.xml` file with a missing `datatype` (see below for example)
3. Configure the camera driver to use this attributes file (`caput -S TEST:cam1:NDAttributesFile attrs.xml`). Note that the path is relative to the IOC working directory.
4. Configure and enable ADPluginKafka and ensure the camera is capturing images

### Expected results

The image is produced to Kafka without the problem attribute.

### Actual results

The IOC crashes with the following error:

```
kafkaCam: ../NDArraySerializer.cpp:178: static DType NDArraySerializer::GetFB_DType(NDAttrDataType_t): Assertion `false' failed.
```

### Example XML file

```xml
<?xml version="1.0" ?>
<Attributes>
        <Attribute name="AcquireTime" type="PARAM" source="ACQ_TIME" datatype="DOUBLE" description="Acquire time (s)" />
        <Attribute name="Gain" type="PARAM" source="GAIN" description="Gain (dB)" />
</Attributes>
```

Note missing `datatype` on the Gain attribute.

## Cause

An `assert(false)` in the `default:` branch of a `switch` statement. Found at [the end of `NDArraySerializer::GetFB_DType`](https://github.com/CentralLaserFacility/ADPluginKafka/blob/191edf1bbb4c754b624ec68abbf5728a84ab1723/ADPluginKafkaApp/src/NDArraySerializer.cpp#L120).

There are several other `assert(false)` statements in that file that should probably also be removed.

### PR DESCRIPTION
**Pull request by btspiers**
Fixes #2

We now skip any attribute with an invalid datatype, and also skip instead of asserting if the attribute value doesn't exist. Making this work nicely entailed changing the while loop to a for loop (would be nice if we could use range-based for, but ADCore says no). 

I also noticed the skipped attribute's name was still showing up in the message payload if I watched the topic using kafkacat, so I did some reordering to avoid that orphan data ending up in the buffer.

I've tested this locally, and I'm able to pull messages with skipped attributes out of kafka and decode them using the ESS streaming-data-types python package.

### CODE REVIEW

File: ADPluginKafkaApp/src/NDArraySerializer.cpp [hunk 1]
```diff
@@ -53,34 +53,35 @@ void NDArraySerializer::SerializeData(NDArray &pArray,
...
-    auto temp_attr_str = builder.CreateString(attr_ptr->getName());
-    auto temp_attr_desc = builder.CreateString(attr_ptr->getDescription());
-    auto temp_attr_src = builder.CreateString(attr_ptr->getSource());
+  // Iterate over attributes, next(ptr) returns NULL when there are no more
+  for (NDAttribute *attr_ptr = pArray.pAttributeList->next(nullptr); attr_ptr != nullptr; attr_ptr = pArray.pAttributeList->next(attr_ptr)) {
     size_t bytes;
     NDAttrDataType_t c_type;
-    attr_ptr->getValueInfo(&c_type, &bytes);
+    int result = attr_ptr->getValueInfo(&c_type, &bytes);
+    if ((ND_SUCCESS != result) | (0 == bytes))
```
Comment (stephen-jd-dann) [inline ADPluginKafkaApp/src/NDArraySerializer.cpp]: You want `||` here (logical OR) not `|` (bitwise OR).

Comment (stephen-jd-dann) [inline ADPluginKafkaApp/src/NDArraySerializer.cpp]: I compared `c_type` against `NDAttrUndefined` instead of comparing `bytes` against `0`.

They're equivalent of course, but you need to inspect the implementation of `getValueInfo` to know that. The condition that we actually care about is that `c_type` is not `NDAttrUndefined`, so that we know the switch statement is exhaustive.

**Review by stephen-jd-dann — CHANGES_REQUESTED** [review]
Largely the same as my own attempt, which is encouraging. The only problem is the use of bitwise OR instead of logical OR.

File: ADPluginKafkaApp/src/NDArraySerializer.cpp (hunk 1 above)
Comment (btspiers) [reply ADPluginKafkaApp/src/NDArraySerializer.cpp]: Good point. I was expecting that something in the rest of the code would misbehave if bytes == 0 for some other reason, but it looks like flatbuffers actually handles that case without problem. I'll check c_type instead

**Review by stephen-jd-dann — APPROVED** [review]
Looks good to me.

Since I don't have much C++ experience, normally I'd be looking for a second review. However, since we came up with almost the same patch independently, we might not need it.
